apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dilek-kumbarasi-beta-pvc
  namespace: dilek-kumbarasi-beta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
