apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dilek-feneri-demo-pvc
  namespace: dilek-feneri-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
